INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (132, 'Afeganistão');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (175, 'Albânia, República da');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (230, 'Alemanha');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (310, 'Burkina Faso');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (370, 'Andorra');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (400, 'Angola');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (418, 'Anguilla');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (434, 'Antigua e Barbuda');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (477, 'Antilhas Holandesas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (531, 'Arábia Saudita');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (590, 'Argélia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (639, 'Argentina');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (647, 'Armênia, República da');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (655, 'Aruba');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (698, 'Austrália');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (728, 'Áustria');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (736, 'Azerbaijão, República do');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (779, 'Bahamas, Ilhas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (809, 'Bahrein, Ilhas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (817, 'Bangladesh');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (833, 'Barbados');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (850, 'Belarus');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (876, 'Bélgica');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (884, 'Belize');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (906, 'Bermudas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (930, 'Mianmar (Birmânia)');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (973, 'Bolívia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (981, 'Bósnia-Herzegovina');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1015, 'Botsuana');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1058, 'Brasil');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1082, 'Brunei');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1112, 'Bulgária, República da');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1155, 'Burundi');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1198, 'Butão');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1279, 'Cabo Verde, República de');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1376, 'Cayman, Ilhas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1414, 'Camboja');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1457, 'Camarões');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1490, 'Canadá');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1504, 'Canal, Ilhas do (Jersey e Guernsey)');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1511, 'Canárias, Ilhas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1538, 'Cazaquistão, República do');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1546, 'Catar');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1589, 'Chile');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1600, 'China, República Popular da');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1619, 'Formosa (Taiwan)');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1635, 'Chipre');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1651, 'Cocos (Keeling), Ilhas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1694, 'Colômbia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1732, 'Comores, Ilhas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1775, 'Congo, República do');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1830, 'Cook, Ilhas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1872, 'Coréia, Rep. Pop. Democrática da');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1902, 'Coréia, República da');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1937, 'Costa do Marfim');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1953, 'Croácia, República da');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1961, 'Costa Rica');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1988, 'Coveite');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (1996, 'Cuba');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2291, 'Benin');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2321, 'Dinamarca');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2356, 'Dominica, Ilha');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2399, 'Equador');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2402, 'Egito');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2437, 'Eritréia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2445, 'Emirados Árabes Unidos');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2453, 'Espanha');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2461, 'Eslovênia, República da');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2470, 'Eslovaca, República');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2496, 'Estados Unidos');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (2518, 'Estônia, República da');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (3654, 'Indonésia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6114, 'Porto Rico');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6238, 'Quênia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6254, 'Quirguiz, República');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6289, 'Escócia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6408, 'República Centro-Africana');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6475, 'República Dominicana');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6602, 'Reunião, Ilha');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6653, 'Zimbábue');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6700, 'Romênia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6750, 'Ruanda');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6904, 'Samoa');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6912, 'Samoa Americana');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (6955, 'São Cristóvão e Neves');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (7820, 'Território Britânico Oc. Índico');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (7838, 'Djibuti');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (7889, 'Chade');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (7919, 'Tcheca, República');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (7951, 'Timor Leste');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8001, 'Togo');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8052, 'Toquelau, Ilhas');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8109, 'Tonga');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8150, 'Trinidad e Tobago');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8206, 'Tunísia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8273, 'Turquia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8281, 'Tuvalu');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8311, 'Ucrânia');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8338, 'Uganda');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8451, 'Uruguai');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8478, 'Uzbequistão, República do');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8486, 'Vaticano, Estado da Cidade do');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8508, 'Venezuela');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8583, 'Vietnã');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8630, 'Virgens, Ilhas (Britânicas)');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8664, 'Virgens, Ilhas (E.U.A.)');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8702, 'Fiji');
INSERT INTO `enderecoPais` (`id`, `nome`) VALUES (8737, 'Wake, Ilha');